name: Deploy

on:
  push:
    branches: [ main ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o code_breaker cmd/code_breaker/*

    - name: Build container image
      run: docker build -t registry.digitalocean.com/nesbitjd/codebreaker:latest .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_CODE }}
           
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600    
      
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/nesbitjd/codebreaker:latest
      
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ./.github/workflows/scripts/docker.sh
